const classes = [
  {
    name: 'CENG420',
    fullName: 'Web Programming',
    semester: 'Spring 2020-2021',
    time: 'MW 17:00-19:00',
    section: 'A',
    instructor: 'Ali Bazzi',
    campus: 'Beirut',
  },
  {
    name: 'CENG420',
    fullName: 'Web Programming',
    semester: 'Spring 2020-2021',
    time: 'MW 17:00-19:00',
    section: 'A',
    instructor: 'Ali Bazzi',
    campus: 'Beirut',
  },
  {
    name: 'CENG420',
    fullName: 'Web Programming',
    semester: 'Spring 2020-2021',
    time: 'MW 17:00-19:00',
    section: 'A',
    instructor: 'Ali Bazzi',
    campus: 'Beirut',
  },
  {
    name: 'CENG420',
    fullName: 'Web Programming',
    semester: 'Spring 2020-2021',
    time: 'MW 17:00-19:00',
    section: 'A',
    instructor: 'Ali Bazzi',
    campus: 'Beirut',
  },
  {
    name: 'CENG420',
    fullName: 'Web Programming',
    semester: 'Spring 2020-2021',
    time: 'MW 17:00-19:00',
    section: 'A',
    instructor: 'Ali Bazzi',
    campus: 'Beirut',
  },
  {
    name: 'CENG420',
    fullName: 'Web Programming',
    semester: 'Spring 2020-2021',
    time: 'MW 17:00-19:00',
    section: 'A',
    instructor: 'Ali Bazzi',
    campus: 'Beirut',
  },
  {
    name: 'CENG420',
    fullName: 'Web Programming',
    semester: 'Spring 2020-2021',
    time: 'MW 17:00-19:00',
    section: 'A',
    instructor: 'Ali Bazzi',
    campus: 'Beirut',
  },
  {
    name: 'CENG420',
    fullName: 'Web Programming',
    semester: 'Spring 2020-2021',
    time: 'MW 17:00-19:00',
    section: 'A',
    instructor: 'Ali Bazzi',
    campus: 'Beirut',
  },
  {
    name: 'CENG420',
    fullName: 'Web Programming',
    semester: 'Spring 2020-2021',
    time: 'MW 17:00-19:00',
    section: 'A',
    instructor: 'Ali Bazzi',
    campus: 'Beirut',
  },
  {
    name: 'CENG420',
    fullName: 'Web Programming',
    semester: 'Spring 2020-2021',
    time: 'MW 17:00-19:00',
    section: 'A',
    instructor: 'Ali Bazzi',
    campus: 'Beirut',
  },
  {
    name: 'CENG420',
    fullName: 'Web Programming',
    semester: 'Spring 2020-2021',
    time: 'MW 17:00-19:00',
    section: 'A',
    instructor: 'Ali Bazzi',
    campus: 'Beirut',
  },
  {
    name: 'CENG420',
    fullName: 'Web Programming',
    semester: 'Spring 2020-2021',
    time: 'MW 17:00-19:00',
    section: 'A',
    instructor: 'Ali Bazzi',
    campus: 'Beirut',
  },
  {
    name: 'CENG420',
    fullName: 'Web Programming',
    semester: 'Spring 2020-2021',
    time: 'MW 17:00-19:00',
    section: 'A',
    instructor: 'Ali Bazzi',
    campus: 'Beirut',
  },
];

export default classes;
